name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2 via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 작업 디렉토리로 이동하거나 생성
            mkdir -p ~/docker-homework
            cd ~/docker-homework

            # Git 저장소 초기화 or 최신화
            if [ ! -d ".git" ]; then
              echo "Initializing git repo..."
              git clone https://github.com/hyeseon0105/docker-homework.git .
            else
              echo "Repository exists. Pulling latest changes..."
              git reset --hard
              git clean -fd
              git pull origin main
            fi

            # 기존 컨테이너, 네트워크, 볼륨 제거
            docker-compose down --volumes --remove-orphans

            # 새로 빌드 및 실행
            docker-compose up -d --build
